version: "2.4"

services:
  api:
    image: ghcr.io/bready-team/bready-backend:latest
    container_name: bready-api-blue
    restart: unless-stopped
    mem_limit: 768m
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: cd
      JAVA_TOOL_OPTIONS: "-Xms256m -Xmx384m -XX:MaxMetaspaceSize=256m"

      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

      JWT_SECRET: ${JWT_SECRET}

      KAKAO_REST_API_KEY: ${KAKAO_REST_API_KEY}

      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      KAKAO_REDIRECT_URI: ${KAKAO_REDIRECT_URI}

      NAVER_CLIENT_ID: ${NAVER_CLIENT_ID}
      NAVER_CLIENT_SECRET: ${NAVER_CLIENT_SECRET}
      NAVER_REDIRECT_URI: ${NAVER_REDIRECT_URI}

      CLOUD_AWS_REGION: ${CLOUD_AWS_REGION}
      CLOUD_AWS_S3_BUCKET: ${CLOUD_AWS_S3_BUCKET}
      CLOUD_AWS_S3_PUBLIC_PREFIX: ${CLOUD_AWS_S3_PUBLIC_PREFIX}
      CLOUD_AWS_CREDENTIALS_ACCESS_KEY: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
      CLOUD_AWS_CREDENTIALS_SECRET_KEY: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY}

      OPENAI_API_KEY: ${OPENAI_API_KEY}