spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 안정화 후 validate로 변경
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

jwt:
  secret: ${JWT_SECRET}
  access-exp: 1800000
  refresh-exp: 1209600000

kakao:
  rest-api-key: ${KAKAO_REST_API_KEY}

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: ${KAKAO_REDIRECT_URI}
  naver:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
    redirect-uri: ${NAVER_REDIRECT_URI}

cloud:
  aws:
    region: ${CLOUD_AWS_REGION}

    s3:
      bucket: ${CLOUD_AWS_S3_BUCKET}
      public-prefix: ${CLOUD_AWS_S3_PUBLIC_PREFIX}

    credentials:
      access-key: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
      secret-key: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY}

recommendation:
  ai:
    enabled: true