upstream bready_active {
    server 127.0.0.1:8081;
}

server {
    server_name bready.site www.bready.site;

    location / {
        proxy_pass http://bready_active;

        proxy_http_version 1.1;
        proxy_set_header Connection "";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 3s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/bready.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bready.site/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    if ($host = www.bready.site) {
        return 301 https://$host$request_uri;
    }

    if ($host = bready.site) {
        return 301 https://$host$request_uri;
    }

    listen 80;
    server_name bready.site www.bready.site;
    return 404;
}